name: Cypress Tests

on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cypress run
              uses: cypress-io/github-action@v4
            - name: Archive test results
              uses: actions/upload-artifact@v3
              with:
                name: cypress videos
                path: cypress/videos/*.mp4
